### ISSUE TITLE
[Question] Ignore folders on cloud

### ISSUE THREAD

**Issue by hildogjr** [germanztz/gnome-shell-extension-rclone-manager#22]
How to ignore complete folders (e.g.: Classroom, Meet Recordings, ...) present on cloud to sync?

I tried to add `,/Meet Recordings/**` to "Files to be ignored" as https://rclone.org/filtering/ proposed. I got no success.

**Comment by germanztz** [comment]
Hi, this is a good one! I assume you trying to modify the sync command parameters in settings. That's the right way to do it. If the rsync parameters aren't working, you may try checking the issues in the rclone [github repo](https://github.com/rclone/rclone/issues) because this extension cannot change the rclone behavior... :_(

**Comment by hildogjr** [comment]
I tried to modify the "file to be ignored" in the intention that it works as the `--exclude=*` (https://rclone.org/filtering/).

In what way (command parameter) the definition "file to be ignored" is passed to rclone?

**Comment by hildogjr** [comment]
I could get the intended result by modifying the sync commad to `rclone sync --exclude="/Classroom/**" --exclude="/Meet Recordings/**" %profile: %source --create-empty-src-dirs`.
