### ISSUE TITLE
extension claims rclone not installed

### ISSUE THREAD

**Issue by mueckinger** [germanztz/gnome-shell-extension-rclone-manager#36]
Version: rclone-manager-v47.0 with GNOME 47

I use rclone installed via homebrew which exists under /home/linuxbrew/.linuxbrew/bin/rclone. It is also on the PATH. This setup worked on previous versions of this extension e.g. on GNOME 46. Now the extension claims that rclone is not installed.

journalctl says:
`GLib.SpawnError: Kindprozess »rclone« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)`
Sorry for the German log.

**Comment by germanztz** [comment]
Hi mueckinger, let me see if I can help (I'm no sure because I dont know every single linux distro, but let try...)

First I need you to give me some debug info:

1. Enable the debug mode in the settings
    
    ![imagen](https://github.com/user-attachments/assets/ff3f504b-7a81-4601-acf1-7ebe419e935f)

1. generate a file with the output of these commands:
1.  Restart the extension or logout

```
journalctl --no-pager --no-hostname --since "1 days ago" -b -g rclone -o cat /usr/bin/gnome-shell &> rclone_extension.log
env &>> rclone_extension.log
rclone --version &>> rclone_extension.log
```
1. Review the file `rclone_extension.log` make sure no personal info is present
1. Upload the file `rclone_extension.log` to a [gist](https://gist.github.com/) and send the link in the response to the issue post

**Comment by mueckinger** [comment]
https://gist.github.com/mueckinger/6d72971daeb6fdd336bbf0b8524e632b

**Comment by germanztz** [comment]
Hi, the problem is that brew only has updated the path in you current terminal window, but not system wide.

The command that updates this path is `eval "$(homebrew/bin/brew shellenv)"`. added to your .profile or somewhere that apply it in all you system

I recommend you install rclone with `apt install rclone` . That will fix the problem

The screenshot shows that in a new terminal rclone stops working until. But when I call eval command, it updates de path and it works again

![imagen](https://github.com/user-attachments/assets/0e542c64-0ee7-475a-b13e-369c57e3d2ed)

Hope that helps!

**Comment by mueckinger** [comment]
Ah, that makes sense. 
I would not recommend to use the apt version of rclone. As you can see in your last screenshot it is terribly outdated (1.60.1 is 2 years old!)
